### ISSUE TITLE
Channelname collisions

### ISSUE THREAD

**Issue by sm00th** [sm00th/bitlbee-discord#10]
When channel names on multiple servers coincide bitlbee will add "_" suffixes to the name until it is unique, which doesn't help to see which one is which.

A possible solution to this is to add an option that will change channel naming convention to #servername.channelname for all channels.

Reported by: @Kays in #5

**Comment by tecknojock** [comment]
I'd very much like all my channels prefixed with a Server name to help keep things organized.

**Comment by omnicons** [comment]
Another somewhat interesting solution to this problem would be to have the plugin generate dummy channels with the server names to separate server channels instead of making the channel names long.

**Comment by sm00th** [comment]
> might be nicer if it just included the first 3 characters of the server

That makes perfect sense, I wonder why I never thought of this. 418a7c7 adds the `server_prefix_len` option that lets you control this, see README for more details.
