### ISSUE TITLE
Manual @mentions Broken

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#12]
Per the latest update, the following are fine:
```
kays: hello
kays_test: hello
```

Manual `@mentions` like:
```
hello @kays
```
does not work. It shows up as plain text. Would be nice to have it work even via
```
hello kays
```
where kays is auto-complete-able.

Maybe a better option would be to check if any word matches a nick? Or would that be too slow of a process? I don't think it has to send the message to the server the millisecond after I hit enter. If it's a second slower, I don't think it's a big deal. But if it is not practical, then manual `@mentions` support would be great.

And if you can also add case-insensitive matching such that:
```
kays: hello
Kays: hello
```
both work, I'd appreciate it. Often times, typing on mobile devices auto-capitalize first letter and this also breaks.

**Comment by sm00th** [comment]
Hm, yes, I should have added `@nick` mentions.

"no-trigger-character mentions" probably won't happen, there are some very big "servers" in discord and traversing that huge list of names for each word in a message(as well as looking up every nick in a message) isn't really an option. It is also probably not a good idea to bring irc's unintentional mention problem to discord.

I'm also not going to implement case-insensitive matches. It is a trivial change, but I don't think it is a right thing to do and highlights should be triggered only on exact match. Besides most(if not all) keyboards have an option to disable auto-capitalization.

**Comment by sm00th** [comment]
`@nick` mentions added in ae894c5

**Comment by Kays** [comment]
I suggested the case-insensitive because people on mobile devices often appear offline the second they focus out of the Discord app. So I can't tab complete because they're no longer show up on Bitlbee, and so typing the nicks correctly in correct cases can be very annoying for some nicks that people use, especially those with spaces.

**Comment by sm00th** [comment]
Fair enough, still don't think this should be default behavior, so added it as an option in 9f9951c.
