### ISSUE TITLE
Pinging users when IRC client doesn't tab them out.

### ISSUE THREAD

**Issue by roughnecks** [sm00th/bitlbee-discord#122]
I cannot tab some people's nicknames - but they're right there chatting - while it works with some others.
Maybe it's an issue with the user list?

How can I do that? Thanks

**Comment by roughnecks** [comment]
I think they were set to "invisible", because I changed the "never_offline" option to "on" and it's working now.

**Comment by sm00th** [comment]
Yes, this is likely to be because of invisible statuses (there were some reports about missing users before but not lately). "never_offline" is the only known workaround for that.

**Comment by roughnecks** [comment]
Sadly I still got the issue. People writing, I go to tab them, nothing happens (no matches).

**Comment by dequis** [comment]
What irc client?

**Comment by roughnecks** [comment]
WeeChat 2.0.1 on Debian Stretch.
