### ISSUE TITLE
unhandled event in journalctl

### ISSUE THREAD

**Issue by CryptoSiD** [sm00th/bitlbee-discord#126]
Hi, 

I'm getting the following error every hour or so in the journalctl log:

discord_parse_message: unhandled event: MESSAGE_DELETE_BULK

**Comment by sm00th** [comment]
Those are leftover debug messages to keep track old/catch new discord events. But at this point it makes no sense to make everyone see them, so starting with 549b05a6c31cbac6628229601567f2054b65eab2 you won't see them without BITLBEE_DEBUG env var set. That commit also moves a couple of leftover errors from g_print to imcb_error.
