### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by lachs0r** [sm00th/bitlbee-discord#127]
Even if you’re not a fan of release management, could you please tag version bumps in the Git repository so that distributions can automatically use them in package metadata?

**Comment by sm00th** [comment]
One step at a time.

But sure, if that helps I'll try not to forget to do this. Are you packaging bitlbee-discord for any distro (trying to keep track of any such efforts) or thats just common practice?

**Comment by lachs0r** [comment]
I maintain a package for openSUSE in the [server:irc devel project](https://build.opensuse.org/package/show/server:irc/bitlbee-discord). It has not yet been submitted to Factory (the “staging” repository for the Tumbleweed rolling release distribution and later stable releases), so it has not landed in the main repositories yet.

Of course, for a rolling distro, it is generally not a problem to package and publish git snapshots (unless they break something all the time), but it’s nice to have known-working releases rather than reading the log and guessing which commit is good for packaging. I’d like snapshots to be an exception (e.g. “upstream hasn’t had a release in more than 6 months and it fixes real issues”) rather than the rule.

Ideally, you would also publish them on the GitHub Releases page, along with a log of user-visible changes and fixes. That means I can just copy your change log for the package metadata and I get notified about them via GitHub’s Atom feed. You can make this process easier by enforcing guidelines for contributions [like mpv does, for example](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#sending-patches), but that is of course entirely up to you.

**Comment by sm00th** [comment]
Ok, thank you for the pointers. I do think making it easier for package maintainers to package bitlbee-discord is important, so I'll try to do better on this front in the future.

**Comment by lachs0r** [comment]
Thank you!
