### ISSUE TITLE
#channel mentions are broken

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#13]
`#channel` do not show up (link) properly in Discord when sent from bitlbee-discord.

**Comment by sm00th** [comment]
Didn't know about these either. This actually doesn't work both ways, i.e. it will show up as <#12312314123> in bitlbee-discord when sent from other discord clients

**Comment by sm00th** [comment]
Both incoming and outgoing `#channel` links should work since af442af.
