### ISSUE TITLE
Breaks push notifications

### ISSUE THREAD

**Issue by ecx86** [sm00th/bitlbee-discord#131]
I have been using bitlbee-discord for quite some time now and I'm very satisfied with the software. However, it seems that discord treats the bitlbee client like a desktop client, and as a result, it thinks I'm constantly active on desktop. This causes it to not send mobile push notifications, which is a big inconvenience. Is there any workaround for this? There seems to be a way to decrease "Push notification AFK timeout" in the Discord settings, but no way to disable it.

**Comment by dgw** [comment]
Have you tried turning `send_acks` off? By default, bitlbee-discord acknowledges every message received, which probably resets the AFK timeout.

**Comment by sm00th** [comment]
I have now idea how discord handles AFK status, but it is very likely that acks are the culprit, so you should try disabling `send_acks`. The only problem is once you disable it - it wont send _any_ acks anymore, which will result in having to mark them read from another client.

**Comment by ecx86** [comment]
Unfortunately, that doesn't seem to work.

**Comment by ecx86** [comment]
Maybe requires `afk: true` in status update?

**Comment by sm00th** [comment]
As discussed in #158 added an `always_afk` option in 870ead9. I don't really use the mobile client so if you could check if it helps this issue that would be awesome.

**Comment by ecx86** [comment]
Hooray it works, at least with send_acks off. I will now test it with send_acks on.

**Comment by ecx86** [comment]
Doesn't work with send_acks on. So, in summary, to fix push notifications you must:
 - set `send_acks` to `off`
 - set `always_afk` to `on`
