### ISSUE TITLE
Disable join and left messages

### ISSUE THREAD

**Issue by disconsented** [sm00th/bitlbee-discord#136]
```
[21:13:50] <-- BraveSloth (BraveSloth@discord) has left #Bui.generaldiscussion
[21:13:51] <-- Serenade (Serenade@discord) has left #Bui.generaldiscussion
[21:13:56] --> BraveSloth (BraveSloth@discord) has joined #Bui.generaldiscussion
```

Any way to disable this?  I am getting a LOT more than I would expect

**Comment by sm00th** [comment]
This is done on the client side, in irssi you can do this:
```
/ignore -channels #chan1,#chan2,#chan3 * JOINS PARTS QUITS NICKS
/ignore -channels #chan1,#chan2,#chan3 -regexp -pattern (away|gone|back|playin|weg|wech|returned) * ACTIONS
```

Other clients should have something similar

**Comment by disconsented** [comment]
I have this setup but I don't really want my database being flooded

**Comment by disconsented** [comment]
https://puu.sh/ziuML/819f273323.png 
![image](https://user-images.githubusercontent.com/1381469/35907470-e6f6390a-0c52-11e8-8d09-3b852262de4a.png) that's roughly 3 minutes worth and then that is repeated for each channel

**Comment by sm00th** [comment]
What database? I am not familiar with Quassel, does it keep a database of all events and this can't be disabled?
Disabling these on bitlbee-discord side is not something that I am willing to do just to silence those as it is likely to affect other things. I know it might be a lot on busy servers, but ignoring solution seem to work for people, you can also try to use `never_offline`.

**Comment by disconsented** [comment]
Quassel basically has an integrated bouncer with infinite scrollback (hence the database) you can hide part/join messages but not ignore them, `never_offline` seems to be working well cheers
