### ISSUE TITLE
Feature request: hide non-friends from the global buddy list

### ISSUE THREAD

**Issue by rr-** [sm00th/bitlbee-discord#138]
After joining a few popular channels, my global buddy list is polluted with hundreds of people I don't know.
Rather than showing them as offline in my global buddy list, I'd rather see them only in relevant channels.

**Comment by sm00th** [comment]
There is such a feature, see "friendhip_mode" in README.

**Comment by rr-** [comment]
But it's set to `on` and I still see random people…

**Comment by rr-** [comment]
Plus they're offline, alright, but I don't want to see them altogether.

**Comment by sm00th** [comment]
Oh, you mean bitlbee's `blist`. Yes, they will still show up there, but iirc you can't have people in channels and not in blist, thats just how bitlbee itself works. The only way to do what you want is not to add people to channels at all (I believe twitter filters work in this fassion). This is an extreme measure for what I consider a rare usecase, so I won't be implementing this myself. Although there might be some work going on on this in #132 which tries to accomplish different goal with the same measures.
