### ISSUE TITLE
Animated emotes aren't replaced, like static ones

### ISSUE THREAD

**Issue by dgw** [sm00th/bitlbee-discord#139]
Animated emotes come through (as of 7375256) as something like `<a:ablobnom:396521774147436554>`.

In Discord's web client, the animated emoji is inserted as an embedded GIF from the URL `https://cdn.discordapp.com/emojis/396521774147436554.gif?v=1`. Looks like it could be pretty simple to infer the GIF URL from the ID given, at least.

I did not find an open issue referencing "animated" when I searched, so hopefully this isn't a duplicate. Maybe I should even try my hand at fixing it myself next week (this week is quite busy IRL).

**Comment by sm00th** [comment]
If you (or anyone) are going to take a stab at it it might be useful to look at #106 (and related #60)

**Comment by dgw** [comment]
\o/

Just as I thought, someone else picked this up when I got busy taking over another project and going through over a year of pull request backlog & accumulated bugs. Thanks, @jwheare!
