### ISSUE TITLE
Set Online/Idle/Do Not Disturb/Invisible status?

### ISSUE THREAD

**Issue by ecx86** [sm00th/bitlbee-discord#154]
Is it possible to set status to 'Online', 'Idle', 'Do Not Disturb', 'Invisible', etc?

Related issue: #25

**Comment by sm00th** [comment]
They did add those statuses: https://discordapp.com/developers/docs/topics/gateway#update-status

Sending those out isn't much trouble, but I wonder how this can be represented on bitlbee's side. It is easy to distinguish between online/idle using `/away`, but others require some kind of interface. I'll need to take a look, maybe some other protocol already does something like this.

**Comment by Alcaro** [comment]
The most obvious one would be string manipulation on the away reason. /away dnd:Mario Kart

**Comment by ecx86** [comment]
What about the `status` variable?

`account discord status set xxxx`

**Comment by ecx86** [comment]
I implemented the changes here https://github.com/ecx86/bitlbee-discord/commit/367f93fd6425d8bbf06613e178203238c7aaad34
