### ISSUE TITLE
/me

### ISSUE THREAD

**Issue by Silver-D** [sm00th/bitlbee-discord#16]
typing /me something in bitlbee-discord results in a literal "/me something" in discord
typing /me something in discord results in \*something\* in bitlbee-discord

**Comment by sm00th** [comment]
Discord's way of handling /me messages is a bit weird but what can you do. 6d881c9 adds these translations.

**Comment by Silver-D** [comment]
Yeaa I can see how weird it is. There may be another weird thing,

In Discord, \*\*TEST\*\* makes text bold.
What happens when someone sends a message starting with a bold word in Discord?
You get /me \*TEST\* in IRC \:P

Also typing \*test\* in IRC results in italics in Discord But I'm assuming this is expected behavior, since /me test and \*test \* do the same thing.

**Comment by sm00th** [comment]
Sending *test* from bitlbee currently works exactly the same way as sending it from discord web, I'll need to check how what sending **test** from discord results in

On January 17, 2016 1:22:49 PM CET, Alex <notifications@github.com> wrote:
>Yeaa I can see how weird it is. There may be another weird thing,
>
>In Discord, \*\*TEST\*\* makes text bold.
>What happens when someone sends a message starting with a bold word in
>Discord?
>You get /me \*TEST\* in IRC \:P
>
>Also typing \*test\* in IRC results in italics in Discord But I'm
>assuming this is expected behavior, since /me test and \*test \* do the
>same thing.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sm00th/bitlbee-discord/issues/16#issuecomment-172318809

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sm00th** [comment]
Just checked: **TEST** and /me *TEST* sent from discord are identical in content, so as fas as I can see bitlbee-discord's behavior is identical to discord in this regard.

**Comment by sm00th** [comment]
Added an option to control whether to translate incoming /me message in a1a4a53
