### ISSUE TITLE
"/away" is not treated as Away by default, keywords

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#161]
## In brief
* Treat `/away` as `idle` unless some special keyword is set
  * Allows `/away` to match expectations of setting oneself, well, Away
  * Allows automatic global `/away` on client detach (*Quassel, ZNC, etc*) to properly set "not here"
* Align with [Bitlbee's chosen `/away` keywords](https://github.com/bitlbee/bitlbee/blob/2b6cb873a5848cbb3ab204da9d0d84970764128f/protocols/nogaim.c#L777-L840 )
  * Allows setting presence to work across protocols
  * Matches [expectations set by Bitlbee documentation](https://www.bitlbee.org/user-guide.html#away )

Criteria | Rank | Reason
---------|---------|-------------
Impact | ★★☆ *2/3* | User-facing statuses, matches expectations from IRC and Bitlbee
Risk | ★★☆ *2/3* | Potentially setting wrong status, changes existing behavior
Complexity | ★★☆ *2/3* | String parsing, matching, documentation changes

## Rationale
Most IRC clients and networks allow one to mark themselves as unavailable using `/away [some message]`.  Unfortunately, IRC does not yet have a way to use other presence levels supported by different protocols.

Bitlbee's approach is to make use of keywords in away messages, mapping them to lower-level protocol presence states.  E.g. `/away Busy - Filing issues on GitHub` would map to Discord's `dnd` and set the status message to `Filing issues on GitHub.`

(*For Discord, if use of `/away` is needed for setting status message, too, `Online - A message` could map to `online`/not AFK with status message of `A message`.*)

Bitlbee also handles `/away` without any matching keywords to mark oneself as away.  This matches assumptions made by clients that automatically set away messages on idle or disconnect from a bouncer.

bitlbee-discord should support these keywords and follow Bitlbee's behavior to reduce confusion, avoid learning new keywords, and avoid interfering with the assumptions made by IRC clients/bouncers.

### [Bitlbee documentation on Away](https://www.bitlbee.org/user-guide.html#away )
*Bold emphasis added*

> ### Away states
>
> **To mark yourself as away, you can just use the `/away` command in your IRC client.** BitlBee supports most away-states supported by the protocols.
>
> Away states have different names across different protocols. BitlBee will try to pick the best available option for every connection: 
>
> * Away
> * NA
> * Busy, DND
> * BRB
> * Phone
> * Lunch, Food
> * Invisible, Hidden
>
> So `/away Food` will set your state to "Out to lunch" on your MSN connection, and for most other connections the default, "Away" will be chosen.
>
> You can also add more information to your away message. Setting it to "Busy - Fixing BitlBee bugs" will set your IM-away-states to Busy, but your away message will be more descriptive for people on IRC. Most IM-protocols can also show this additional information to your buddies.
>
> If you want to set an away state for only one of your connections, you can use the per-account `away` setting. See `help set away`.

---
*If needed, this issue will be updated with more details later on.*

**Comment by sm00th** [comment]
Thanks for such a detailed report, this really helped to make this easy. I actually thought that we were already doing this because of:

> So /away Food will set your state to "Out to lunch" on your MSN connection, and for most other connections the default, "Away" will be chosen.

What I didn't realize is that 98f3893 changed that default to 'online' resulting in this weird behavior.

Please reopen if anything is missing.
