### ISSUE TITLE
[Enhancement] Add option to disable custom emote link sending

### ISSUE THREAD

**Issue by nermolov** [sm00th/bitlbee-discord#169]
I'm in a very large discord server that people constantly use custom emotes in, often in the middle of sentences. It would be helpful if there could be an option to disable the bridge's functionality of sending the url of custom emotes.

**Comment by sm00th** [comment]
Ah yes, I see how it could be annoying in emoji-spamming channels. fd8213f adds an option to disable emoji urls.
