### ISSUE TITLE
This plugin requires bitlbee-libpurple

### ISSUE THREAD

**Issue by y-viel** [sm00th/bitlbee-discord#173]
This is not documented anywhere. Please add this to the description, so that other people might be spared headaches as to why the plugin is not recognized. It won't work with bitlbee alone.

Thank you very much :)

**Comment by sm00th** [comment]
Hi, this plugin never required bitlbee-libpurple to work and I don't have it installed on any of my machines. Are you sure you are not confusing this one with https://github.com/EionRobb/purple-discord

**Comment by y-viel** [comment]
Thank you very much for your quick reply. Yes, I'm very sure that this is the plugin :)
When using bitlbee, the plugin doesn't show up in the list. Using bitlbee-purple, it does. I have tested this on an Ubuntu 16.04 LTS machine, using the bitlbee repos.

**Comment by Alcaro** [comment]
I'm using this plugin on Debian stable (9, Stretch). Like sm00th, I don't have bitlbee-libpurple installed, it works fine without that.

Definitely strange. Maybe you forgot sudo make install, or you (or your distro) changed some config in strange ways? For example, maybe you've got a Protocols= setting in /etc/bitlbee/bitlbee.conf?

**Comment by y-viel** [comment]
No, the "Protocols" line is commented out.
Question: Is it possible to compile the binary on a machine, and copy it to another one, provided both are running the same architecture?
