### ISSUE TITLE
Batch channel mapping

### ISSUE THREAD

**Issue by rzumer** [sm00th/bitlbee-discord#174]
Mapping channels manually can be quite tedious. In the chatroom list, channels already have short form names composed of an abbreviation of the server name, followed by a period and the channel name. I propose a command that would attempt to map all channels of a particular server (or even all channels on an account) to their short names, and return any channel name collision for the user to remap themselves.

This might be better done on the bitlbee side; if there is a way to do it currently that is not well-documented please mention it in the readme.

**Comment by sm00th** [comment]
Ah, something has been added some time ago, namely auto_join and auto_join_exclude options. They even had proper description in the docs, but I (and the patch author as well) forgot to add it to the README. ba47eed takes care of that.

I think that is the closes we can get to what you have in mind.

**Comment by rzumer** [comment]
It does, thank you.
