### ISSUE TITLE
undefined symbol: lws_set_log_level

### ISSUE THREAD

**Issue by rookiejet** [sm00th/bitlbee-discord#18]
Starting the plugin crashes bitlbee with the following error:

/usr/lib/bitlbee/discord.so: undefined symbol: lws_set_log_level

Compiled with latest source for libwebsockets, version 1421.8d5351a-1

**Comment by sm00th** [comment]
Just rebuilt both newest libwebsockets and discord-bitlbee and everything works just fine, [the function is there](https://github.com/warmcat/libwebsockets/blob/ba119e90579eeb79849dbd794a539764c0dda300/lib/libwebsockets.h#L1398) so I guess something went wrong during linking, can you do `ldd /usr/lib/bitlbee/discord.so` and see if it is linked against a proper libwebsockets.so and that it is accessible?

**Comment by rookiejet** [comment]
That was indeed the issue. Thanks.
