### ISSUE TITLE
Unable to send messages after joining to a channel

### ISSUE THREAD

**Issue by roitto** [sm00th/bitlbee-discord#186]
After joining to an discord channel, it is possible to send only one message. After that it's not possible to send any other messages. To send another message, you need to restart the whole IRC client. The messages appears right on the IRC client but they wont appear on the discord side. It also doesn't throw any errors whatsoever. 

Receiving messages works fine.

**Comment by dgw** [comment]
?

**Comment by roitto** [comment]
I updated my bitlbee-discord version, restarted bitlebee service and restarted my IRC client and the problem went away. I am unable to repeat this so i closed the issue.

**Comment by Alcaro** [comment]
Symptoms seem identical to #182, so yes, fixed recently.
