### ISSUE TITLE
Broken Smiley/Emoticon

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#19]
Using any emotes:
```
:O :( :) :D
```
does not get converted properly in Discord. Likewise, emotes used in Discord do not show up in bitlbee-discord.

**Comment by sm00th** [comment]
"Broken" is not exactly the right word for it. It is a missing feature that I am not willing to implement and/or maintain as it is just a list of questionable transformations. I mean discord's webclient does transform `:)` into `😃` but that is something they chose to do, not a protocol requirement and it doesn't really break anything, you can send that character from bitlbee-discord and get a smiley in discord-webclient, and it can be properly displayed in your irc client with the right fonts if you care about things like that, some irc clients might even give you an ability to maintain your list of replacements where you can implement a feature like that.

**Comment by Kays** [comment]
well, it's not working for me.

http://imgur.com/tH9hqMt.png
http://imgur.com/Y7JZ85V.png

**Comment by sm00th** [comment]
I meant that if you copy and paste(or enter with it's code) the 😃 symbol into your irc client it will show up properly on discord's webapp side.
