### ISSUE TITLE
Token expried

### ISSUE THREAD

**Issue by raccoondude** [sm00th/bitlbee-discord#193]
I am unable to sign into discord, 

Once I try

```
acc discord on
````

I get: ```
 discord - Logging in: Token expired, cleaning up       x
18:00:55  @root | discord - Logging in: Signing off..                    x
18:00:55  @root | discord - Logging in: Reconnecting in 5 seconds..      x
18:01:00  @root | discord - Login error: Login error: captcha-required   x
18:01:00  @root | discord - Logging in: Signing off..           
```

I made sure the token and email and password where correct

Nothing seems to work!

**Comment by raccoondude** [comment]
also, I don't receive a email

this is also a brand new account I made just for Bitlbee

**Comment by sm00th** [comment]
The only currently known way to login when discord is asking for catpcha is login with your browser and then set authentication token in bitlbee-discord. You can find more info on how to do that in https://github.com/sm00th/bitlbee-discord/issues/118

**Comment by raccoondude** [comment]
Yeah, I know

But isn't that what I did by setting my token with ```acc discord set token_cache <token>```

**Comment by sm00th** [comment]
Oh, sorry, I missed the token messages.You get the "token expired" message when server does not accept the token you provide, so the email/token pair is somehow incorrect.

**Comment by raccoondude** [comment]
Yeah, for some reason the token was cut off in both the Local Storage and the Memory,

but I got a friend to give me the token
