### ISSUE TITLE
Bitlbee wont change channels

### ISSUE THREAD

**Issue by raccoondude** [sm00th/bitlbee-discord#194]
For some reason, when I add a new discord channel with ```chat add discord !1 <server>.<channel>``` it will give me a random channel and no matter what I do i get sent to that channel

This happens on all servers

**Comment by raccoondude** [comment]
and it works normally besides for that,

you can send messages, receive them, everything but change the channel,

When i exit and go back it send me back to the same channel on that server

**Comment by Alcaro** [comment]
Are you replacing !1 with the real ID (index in `chat list discord`)? The channel name only shows up in your irc client, it doesn't need to be the same as what the server says. You can rename channels locally (for example, if there are three #general in different categories, you can use `chat add discord !18 #food-general`).

**Comment by raccoondude** [comment]
No, how do I find the ID of the channel

**Comment by raccoondude** [comment]
Ok, found out how,

my RPI screen didn't show the index due to a console glitch with LCD-show, 

its been fixed :D
