### ISSUE TITLE
Custom install directory doesn't work

### ISSUE THREAD

**Issue by La-Loutre** [sm00th/bitlbee-discord#198]
Hello,
I don't really have time to go into source code to add this feature.
If someone is interested, I would be very grateful because I don't want to install it as root.

```bash
./autogen.sh && \
    ./configure --prefix=$HOME/my/dir && \
    make && \
    make install 
```

/usr/ prefix stuff:
```bash
make[2]: *** [Makefile:414: install-libLTLIBRARIES] Error 1
make[1]: *** [Makefile:628: install-am] Error 2
```

Thanks for bitblee-discord anyway.

**Comment by sm00th** [comment]
`bitlbee-discord` does not use prefixes because it installs into bitlbee's plugin dir, you can override it with `--with-plugindir <path>` option to `./configure` but bitlbee won't pick it up if it is in a wrong directory.

**Comment by La-Loutre** [comment]
My bad, thanks.
