### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Sightline-Networks** [sm00th/bitlbee-discord#20]
I installed this from the AUR. The error I'm getting is:
`bitlbee[19007]: /usr/bin/bitlbee: symbol lookup error: /usr/lib/bitlbee/discord.so: undefined symbol: lws_set_log_level`
This is making Bitlbee crash, let me know if you need more info.

**Comment by Sightline-Networks** [comment]
Ok I'm not entirely sure if this is your issue, or the maintainers issue. I changed
`PKG_CONFIG_PATH="/usr/lib/lib64/pkgconfig" LIBWEBSOCKETS_LIBS="-L/usr/lib/lib64" ./configure`
to
`PKG_CONFIG_PATH="/usr/lib/lib64/pkgconfig" LIBWEBSOCKETS_LIBS="-L/usr/lib/lib64 -lwebsockets" ./configure`

and it worked.

**Comment by sm00th** [comment]
Yeah, it is arch-specific problem, when I sent the patch to aur package I didn't realize it will completely override LIBWEBSOCKETS_LIBS, so your change should help, but it is actually not the proper way to solve this. What should be done is libwebsockets-git in aur should be fixed to install into proper paths.

**Comment by ikn** [comment]
On armv6h architecture, it worked for me with just './configure'.

**Comment by sm00th** [comment]
Yes, the problem seems to be only on x86_64

**Comment by sm00th** [comment]
Shouldn't be an issue anymore since libwebsockets dependency is dropped in d00ef51.
