### ISSUE TITLE
Unable to connect to discord: Connection timeout

### ISSUE THREAD

**Issue by xrogaan** [sm00th/bitlbee-discord#201]
As of today, bitlbee discord seems unable to reach discord at all:

```
<root> discord - Login error: Connection timeout
<root> discord - Logging in: Signing off..
<root> discord - Logging in: Reconnecting in 5 seconds..
<root> discord - Login error: Connection timeout
<root> discord - Logging in: Signing off..
<root> discord - Logging in: Reconnecting in 15 seconds..
<root> discord - Login error: Connection timeout
<root> discord - Logging in: Signing off..
<root> discord - Logging in: Reconnecting in 45 seconds..
```

Not quite sure what it means, maybe a change in API? I am obviously connected to the internet and able to reach discordapp.com, `host` returns a bunch of ip and all.

**Comment by xrogaan** [comment]
Discussed this over IRC and provided a log. Discord is timing me out because data isn't processed fast enough. Updating to bitlbee 3.6 doesn't improve anything. Left most server I was on, without improvements.

I usually get high CPU usage when connecting, but no more. The change in behavior didn't occur after I made changes to my configuration or the amount of server I was on, which lead me to believe that something changed on discord's end.

Smell test suggest to me that processing the data might need to be done at a later stage.

**Comment by remlap** [comment]
I am seeing the same issue. I can connect but very soon after connect drops and won't reconnect.

**Comment by sm00th** [comment]
The opcode and format are still valid though because it doesn't disconnect right away (it should on invalid opcode or badly formatted request).

**Comment by sm00th** [comment]
Pushed in a workaround. I am not sure of all effects it will have, but at least it lets you login.

**Comment by remlap** [comment]
Still seeing discord - Logging in: Signing off..

**Comment by AxelTerizaki** [comment]
Thanks for the quick fix ! :)

**Comment by sm00th** [comment]
@remlap make sure you logout from bitlbee and restart it after installing updated plugin

**Comment by remlap** [comment]
> @remlap make sure you logout from bitlbee and restart it after installing updated plugin

I quickly deleted my comment after I realised what I did wrong, I had stupidly run make then forgot to actually install! I even restarted bitlbee. I am an idiot!

It seems to be all working well.

**Comment by namtsui** [comment]
I experienced this timeout issue as of February 4 and will try your fix. Thanks.

**Comment by xrogaan** [comment]
Works for me.

**Comment by xrogaan** [comment]
Login works for me.

**Issue introduced:** the user lists are now empty.

**Comment by crazycatdevs** [comment]
Hi there,
Just to say that the fix worked for me. I think the issue could be close.

**Comment by sm00th** [comment]
1b9870a adds support for per-channel sync, so user lists should be there once again.

**Comment by normen** [comment]
Seeing the same behavior again, can't seem to log in to discord using the plugin.

**Comment by demlak** [comment]
and again..
```
23:56 <@root> discord - Login error: Connection timeout
23:56 <@root> discord - Logging in: Signing off..
23:56 <@root> discord - Logging in: Reconnecting in 5 seconds..
23:58 <@root> discord - Login error: Connection timeout
23:58 <@root> discord - Logging in: Signing off..
23:58 <@root> discord - Logging in: Reconnecting in 15 seconds..
00:00 <@root> discord - Login error: Connection timeout
00:00 <@root> discord - Logging in: Signing off..
00:00 <@root> discord - Logging in: Reconnecting in 45 seconds..
00:03 <@root> discord - Login error: Connection timeout
00:03 <@root> discord - Logging in: Signing off..
00:03 <@root> discord - Logging in: Reconnecting in 135 seconds..
00:07 <@root> discord - Login error: Connection timeout
00:07 <@root> discord - Logging in: Signing off..
00:07 <@root> discord - Logging in: Reconnecting in 405 seconds..
```

**Comment by sm00th** [comment]
I am currently able to log in normally. But if the issue persists for you please follow the 'Debugging' section from readme and open a new issue with debug information included.

**Comment by demlak** [comment]
thx.. see: #218
