### ISSUE TITLE
Disconnects Seemingly at Random, Connection Times Out Does Not Reconnect

### ISSUE THREAD

**Issue by tomatosoupcan** [sm00th/bitlbee-discord#202]
Having a weird issue since an internet outage the other day. After some time I will get disconnected from Discord and it will continuously attempt to reconnect and timeout. If I manually "account discord off" "account discord on" it will start working again for a bit. Currently running debug mode to try to see if I can catch the issue, but posting ahead of that in case this is some known issue with a solution already.

**Comment by tomatosoupcan** [comment]
Think this may have been fixed by updating to the newest pull, will update and close if so

**Comment by sm00th** [comment]
So, did the latest commits help?

**Comment by rtyler** [comment]
@sm00th For what it's worth, I recently had similar issues as @tomatosoupcan described, and a fresh rebuild today seems to have resolved them. Thanks! :smile_cat:

**Comment by sm00th** [comment]
Considering this fixed by latest updates for now.
