### ISSUE TITLE
Rename README to README.md

### ISSUE THREAD

**Issue by Jonta** [sm00th/bitlbee-discord#206]
Already formatted pretty Markdown-y, and .md would make GitHub understand

**Comment by sm00th** [comment]
I dumped it into https://jbt.github.io/markdown-editor/ to see how that will look and it is not pretty, in fact to me it is less readable than it is now. If you are interested enough to do a proper conversion and pretty things up - I'll accept a pull request.

There was already an attempt to do this and it looked mostly good, but I had a minor request and the author just disappeared: https://github.com/sm00th/bitlbee-discord/pull/112
