### ISSUE TITLE
Reconnect requested

### ISSUE THREAD

**Issue by fuzzy76** [sm00th/bitlbee-discord#207]
Every 2 hour I see this in &bitlbee:
```
19:21 <@root> discord - Reconnect requested
19:21 <@root> discord - Performing soft-reconnect
```

**Comment by dequis** [comment]
Sounds fine?

**Comment by fuzzy76** [comment]
Yes, the connection stays. But is it supposed to spam &bitlbee with info messages like that? It's bothersome to see the &bitlbee channel marked with unread messages constantly.

**Comment by sm00th** [comment]
It is hardly 'spamming' being once in 2 hours. I do agree different users may have different preferences on whether they want to see things like that but there are already way to many toggles in bitlbee discord and if you really don't want to see this you can use your irc client's `ignore` functionality to silence these.

**Comment by fuzzy76** [comment]
I would assume that output to &bitlbee would be messages I needed to be aware of, not routine handshakes. As it is now, 95% of the traffic in my &bitlbee is discord so it doesn't look like the regular verbosity level for bitblee plugins.

Unfortunately, my IRC client ([The Lounge](https://thelounge.chat)) does not come with a way to ignore those messages.
