### ISSUE TITLE
Discord's new reply feature

### ISSUE THREAD

**Issue by mkaito** [sm00th/bitlbee-discord#215]
For those of you who (sensibly) don't use the Electron client very much, Discord has added a new Reply feature, which quotes and pings a user. None of which is visible to us. It makes valuable context completely invisible to us.

Now, I'm not a huge fan of the feature itself, but Discord added it, and people use it, so we ought to be able to follow a conversation at least.

**Comment by runrin** [comment]
+1 for this request.

it is often very confusing to know what people are talking about without a way to see which message is being replied to. i kinda have to keep the web discord open to be able to follow conversations.

**Comment by sm00th** [comment]
Yeah, this can get pretty confusing. I guess that can be implemented the same way bitlbee does with twitter, i.e. prefix every message with a unique id.

**Comment by runrin** [comment]
> Yeah, this can get pretty confusing. I guess that can be implemented the same way bitlbee does with twitter, i.e. prefix every message with a unique id.

this would also make edits easier to identify.

**Comment by Thaodan** [comment]
> Yeah, this can get pretty confusing. I guess that can be implemented the same way bitlbee does with twitter, i.e. prefix every message with a unique id.

Or simpler (if so wanted) by doing something similar to purple-telegram:
> foobar wrote:
> foobar stuff

**Comment by Linkandzelda** [comment]
Have to add a +1 for this. It just became almost impossible to follow anything in a big channel without having the client open to check context.

**Comment by sm00th** [comment]
I know this has been a long while but I just pushed a very rough commit implementing this (the way @Thaodan suggested) to a separate branch: https://github.com/sm00th/bitlbee-discord/commit/068ed17a752d82ffc5cb075349df6fc20831b462. This is mostly untested so I am planning to keep it there for a week or two before merging, but if anyone is interested in testing - feel free to build that branch and let me know if anything comes up.
