### ISSUE TITLE
Support for unicode nick

### ISSUE THREAD

**Issue by alama** [sm00th/bitlbee-discord#22]
The plugin does not seem to have support of users with Unicode nicks, like "メカラッピーダイラト"
They do not show up in the NickList and all chat messages show with the nick _ (and again _ is not listed in the nicklist)

Only after reconnecting, _ show up in the nicklist, but this is still not the correct

Do not know if this a limit of the plugin or bitlbee

**Comment by sm00th** [comment]
Did you enable utf8 nicks in bitlbee? If I remember correctly they are disabled by default. You can check it with `set utf8_nicks` and enable with `set utf8_nicks true`.

**Comment by alama** [comment]
yea, utf8_nicks was not turn on, `set utf8_nicks true` fixes the issues, thank you
