### ISSUE TITLE
Failed to switch to websocket mode

### ISSUE THREAD

**Issue by ghost** [sm00th/bitlbee-discord#227]
A few days ago I started getting this message and haven't been able to resolve it. Is anyone else experiencing this?

`discord - Login error: Failed to switch to websocket mode`

**Comment by sm00th** [comment]
Looks like https://github.com/sm00th/bitlbee-discord/issues/226, try updating.

**Comment by ghost** [comment]
That was it, thanks. I'll submit a request for the package to be updated in my package manager.
