### ISSUE TITLE
HTTP 400 errors with OTR policy of 'opportunistic'

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#24]
With ```set otr_policy opportunistic```, I consistently received HTTP 400 errors, e.g.
```
<root> discord - Error: Failed to send message (400).
```

After using ```set otr_policy manual```, messages appear to send correctly and show up in the Discord web interface.  I'm guessing the whitespace and tab pattern interferes with what Discord expects, but I do not know for sure.

Any way to fix this other than ```manual```?  It'd be useful to preserve ```opportunistic``` for protocols where others may or may not be using OTR.

**Comment by sm00th** [comment]
Tabs sent by otr were the reason of this. Fixed in  bd1fcd0. Thanks for the report.

**Comment by sm00th** [comment]
d
