### ISSUE TITLE
Implement away status for account (if protocol allows)

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#25]
In testing, ```/away Reason for away```, ```set away "Reason for away"```, and ```account discord set away "Reason for away"``` do not propagate to the Discord plugin.

I'm not sure how to set status as the web interface doesn't seem to allow changing it and the Linux client doesn't yet exist.  [Discord's help indicates](https://support.discordapp.com/hc/en-us/articles/211374998-What-do-those-colored-dots-next-to-my-avatar-mean- ) that it's supposed to happen after some time of being away-from-keyboard, but doesn't indicate if the client controls this.  Requesting more status options for the official client is [voted as the number 1 suggestion on Discord's feedback page](https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/10831026-user-status-to-appear-as-busy-away-dnd-or-offlin ), so.. this -might- have to wait for a protocol change.

*In my particular case, I have Bitlbee behind Quassel IRC, which stays connected all the time [via the Quassel "core"](http://bugs.quassel-irc.org/projects/quassel-irc/wiki#Introduction ).  When I close the client, the core sends to Bitlbee ```/away [detach_message]```.  Next time the client reconnects, it's cleared by sending Bitlbee a blank ```/away```.*

**Comment by sm00th** [comment]
Some info on idle status can be found in "Gateway Status Update" section of [discord-api-docs](https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/GATEWAY.md).

**Comment by sm00th** [comment]
Added support for away state (idle in discord) with messages and statuses (aka away messages without being away, `help set status`) in  f9b0ec3.
