### ISSUE TITLE
Apply incoming_me_translation to private messages, too

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#27]
Right now, [```incoming_me_translation```](https://github.com/sm00th/bitlbee-discord/blob/710d3f90e79b681fbf7cd3de07a3f8e2151a2b3d/src/discord-handlers.c#L401-L411 ) [affects channel messages](https://github.com/sm00th/bitlbee-discord/blob/710d3f90e79b681fbf7cd3de07a3f8e2151a2b3d/src/discord-handlers.c#L374-L415 ), but [not private messages](https://github.com/sm00th/bitlbee-discord/blob/710d3f90e79b681fbf7cd3de07a3f8e2151a2b3d/src/discord-handlers.c#L370-L373 ).  As the ```/me``` command works in both situations in the official webclient, if possible, the Bitlbee Discord plugin should apply the translation to both situations.

It might simplify matters to move the code into a dedicated function for parsing incoming me strings.

**Comment by sm00th** [comment]
Yup, you are right. Fixed in 0fc96b6.
