### ISSUE TITLE
Control channel with show_users "online,away,offline" still generate joins/quits

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#29]
For control channels, with ```channel set show_users "online,away,offline"``` to always keep offline users visible (*I distinguish using away message thanks to ```away-notify``` support*), anyone who goes offline will quit then immediately rejoin, filling up the log, like so:

```
[1:53:52 am] <BitlbeeNick> channel set show_users "online,away,offline"
[1:53:52 am] --> DiscordUser (DiscordUser@discord) has joined &discord
[1:53:52 am] <root> show_users = `online,away,offline'
[...trimmed many entries...]
[2:48:36 pm] <-- DiscordUser (DiscordUser@discord) has quit (Leaving...)
[2:48:36 pm] --> DiscordUser (DiscordUser@discord) has joined &discord
[2:49:46 pm] <-- DiscordUser (DiscordUser@discord) has quit (Leaving...)
[2:49:46 pm] --> DiscordUser (DiscordUser@discord) has joined &discord
[2:55:10 pm] <-- DiscordUser (DiscordUser@discord) has quit (Leaving...)
[2:55:10 pm] --> DiscordUser (DiscordUser@discord) has joined &discord
[2:58:17 pm] <-- DiscordUser (DiscordUser@discord) has quit (Leaving...)
[2:58:17 pm] --> DiscordUser (DiscordUser@discord) has joined &discord
[3:01:22 pm] <-- DiscordUser (DiscordUser@discord) has quit (Leaving...)
[3:01:22 pm] --> DiscordUser (DiscordUser@discord) has joined &discord
```

With the default of ```online+,special%,away```, or a non-default of ```online,away```, the join/quit spam stops, replaced by nicks disconnecting and reconnecting.  That.. works, but isn't desirable as it forces using the ```blist all``` command to see when new users join.

Chat channels (as opposed to control channels) have no option to show offline users, so the issue doesn't apply there.

Admittedly, I don't know if Bitlbee's plugin interface is responsible, or if the Discord plugin isn't handling the situation properly.

**Comment by sm00th** [comment]
Tried this, and I can't reproduce it with BitlBee-3.4.1+20151227+master+124-gba7618d-git and latest bitlbee-discord. Are there any other settings that can affect this that you are using? Can you try this with latest bitlbee?

**Comment by digitalcircuit** [comment]
I'm still encountering it with the Bitlbee [nightly Debian repository](https://code.bitlbee.org/debian/README.html) on Ubuntu 16.04 and the most recent bitlbee-discord (c71bc109e5d9b64ce0398a3bd4ed750c4cc46f67).  Notably, I'm not using the primary control channel, but a secondary one specific to Discord.

### Relevant settings
**Main control channel - &bitlbee**
```
<BitlbeeNick> channel set
<root> account is empty
<root> auto_join = `true'
<root> fill_by = `!protocol'
<root> group is empty
<root> protocol = `discord'
<root> show_users = `online+,special%,away'
<root> type = `control'
<BitlbeeNick> account discord set
<root> auto_connect = `true'
<root> auto_reconnect = `true'
<root> away is empty
<root> edit_prefix = `EDIT: '
<root> host = `discordapp.com'
<root> incoming_me_translation = `on'
<root> max_backlog = `50'
<root> mention_ignorecase = `off'
<root> mention_suffix = `[:,]'
<root> nick_format is empty
<root> nick_source = `handle'
<root> password = `********' (hidden)
<root> send_acks = `on'
<root> status = `Bitlbee IRC bridge'
<root> tag = `discord'
<root> urlinfo_handle = `urlinfo'
<root> username = `[EMAIL]@gmail.com'
<root> voice_status_notify = `off'
```
**Discord control channel - &discord**
```
<BitlbeeNick> channel set
<root> account is empty
<root> auto_join = `false'
<root> fill_by = `protocol'
<root> group is empty
<root> protocol = `discord'
<root> show_users = `online,away,offline'
<root> type = `control'
```

**Comment by sm00th** [comment]
Copied those settings one to one and I still can't reproduce this issue.

**Comment by digitalcircuit** [comment]
That's odd.  Perhaps something else is amiss in my configuration, though the only other thing that comes to mind is having an ```away-notify```-capable IRC client (*Quassel 0.13-git-e6788734*).

Sometime between now and university mayhem winding down (finals, etc), I'll try a fresh Ubuntu 16.04 container/VM and configure Bitlbee + bitlbee-discord from scratch to see if I can still reproduce the issue.

**Comment by digitalcircuit** [comment]
After some discussion with @dequis on the topic, one idea was bitlbee-discord implementing a ```offline_users_as_away``` setting (*needs a better name*) so offline users only show up as another away state, rather than entirely offline.  This would get rid of the join/quit spam for Discord while still allowing quits for other accounts where they're significant, e.g. XMPP with long-lived sessions.

So it doesn't get lost to the ether of Internet, here's a trimmed snippet of relevant discussion:

*Context: ```offline_users_quit``` being set to ```true``` by default in Bitlbee.*

> **[dx]** digitalcircuit: yep that's exactly it
> **[digitalcircuit]** dx: Ah, nice!  Per-account would be useful (e.g. Discord generates tens to hundreds of quits a day, XMPP is.. 1 or 2), but that's not required.  [...]
> **[dx]** show_users isn't per-account either
> **[dx]** the main problem is that quits are a global thing, and what's changed by show_users is per-channel
> **[dx]** i mean, when an irc user quits, it quits everywhere
> **[digitalcircuit]** However, offline_users_quit could be per-account.  It affects all nicks -from that account-, specifying whether they quit-then-join-relevant-channels where show_offline is true, or only leave (no quit) in channels where show_offline is false.
> **[dx]** why would you want to have offline_users_quit enabled for a subset of your accounts, in that case?
> **[digitalcircuit]** For accounts where it's meaningful if a user goes offline.
> **[digitalcircuit]** Discord keeps track of offline messages and delivers them almost identically, and offline seems to happen much more often.  XMPP delivers offline, too, but I have OTR enabled (may cause issues) and with the contacts I have on XMPP, it's generally more meaningful when they quit - they closed the client, not just a brief interruption of service.
> **[digitalcircuit]** This is potentially a specialized use-case, and I'd understand not wanting the maintenance burden, whatever that may be.
> **[dx]** i don't think the solution to this problem should go through offline_users_quit
> **[dx]** it might make more sense to have things like discord or facebook not announcing offline states, just making that another 'away'
> **[dx]** or a per-account setting to turn offline into away
> **[digitalcircuit]** Offline vs away has some minor significance, so.. per-account setting for those types of chat systems might work best.  [...]

**Comment by sm00th** [comment]
Added an option for this, can you try it out in your setup?

**Comment by digitalcircuit** [comment]
I've updated the bitlbee-discord plugin on my server and enabled the ```never_offline``` option.  Later this evening after verifying it works, I'll go ahead and close this bug report.

Thanks for your time and effort spent on this fix!
