### ISSUE TITLE
Use of libwebsockets is GPL-incompatible

### ISSUE THREAD

**Issue by EionRobb** [sm00th/bitlbee-discord#30]
libwebsockets has an advertising clause in it that makes it GPL-incompatible. https://github.com/warmcat/libwebsockets/blob/master/LICENSE#L18-L23 is the part of the license in question, and http://www.gnu.org/licenses/gpl-faq.en.html#OrigBSD probably explains why it's incompatible.

Using an OpenSSL-compiled version of libwebsockets would be GPL-incompatible too, but the licensing terms are probably more bad than the use of OpenSSL.

**Comment by sm00th** [comment]
Ouch, thats another reason to finally rewrite everything using libsoup that is at least stable and is under LGPL without any exceptions as far as I see.

**Comment by EionRobb** [comment]
Do you need to go as far as using libsoup?  Both libwebsockets and libsoup are doing 90% of what (i'm assuming, if it's anything like what libpurple) is doing under the hood, TCP/SSL connections.

I coded up my own basic websockets usage as part of the Pushbullet libpurple plugin, which certainly doesn't do 100% of what the websockets protocols are capable of, but might be enough for what Discord needs (or at least might be a starting point if you don't want to drag in another heavy dependency like libsoup)? https://github.com/EionRobb/pidgin-pushbullet/blob/master/libpushbullet.c#L256-L382

**Comment by sm00th** [comment]
Nice, thanks for the pointer, I'll certainly look into this option.

**Comment by dequis** [comment]
I emailed licensing@fsf.org about this, as suggested by the GPL FAQ. Their reply:

> Hello and thank you for writing in.
>
>> Hi. The libwebsockets project uses a license that is based on LGPL 2.1
>> with a few exceptions.
>
>> The full text is available here:
>
>> https://github.com/warmcat/libwebsockets/blob/master/LICENSE
>
>> The second exception reads:
>
>> >2) You do not have to provide a copy of the libwebsockets license with
>> >programs that are linked to the libwebsockets library, nor do you have to
>> >identify the libwebsockets license in your program or documentation as
>> >required by section 6 of the LGPL.
>> >
>> >However, programs must still identify their use of libwebsockets. The
>> >following example statement can be included in user documentation to
>> >satisfy this requirement:
>> >
>> >"[program] is based in part on the work of the libwebsockets  project
>> >(https://libwebsockets.org)"
>
>> Someone pointed out that this is equivalent to the BSD advertising
>> clause. I think this is closer to the following part of the
>> Independent JPEG Group license, which is included in the list of GPL
>> compatible licenses in the GNU website.
>
>> >(2) If only executable code is distributed, then the accompanying
>> >documentation must state that "this software is based in part on the work of
>> >the Independent JPEG Group".
>
>> So, is it safe to use libwebsockets in a GPL project? Should they make
>> any changes to the wording of the exception to make it unambiguous?
>
>> Thanks for your time.
>
> My reading of the text is that they have only provided exceptions to the
> terms of the LGPL. The requirement to provide notice with each copy of
> the work that the Library is used in it is already a part of the LGPL,
> so they aren't adding a new requirement by merely spelling that out.
>
> So with the disclaimer that I am not a lawyer and cannot provide you
> with a legal opinion or assurance, I hope this is of help.

**Comment by sm00th** [comment]
Aha, I wonder if it being listed in "requirements" is an enough of a notice. Anyway I was thinking about moving on to something else for a long time and I'll leave this open to track that effort.

**Comment by sm00th** [comment]
The plugin is libwebsockets-free since d00ef51. Thanks.
