### ISSUE TITLE
Nicklist inaccurate when common user exists on mutiple servers

### ISSUE THREAD

**Issue by mumixam** [sm00th/bitlbee-discord#31]
When you share multiple servers with the same user they only appear in the nicklist of 1 server which seems to be the 1st server sorted by alphabet

```UserA is a member of ServerA```
```UserA is a member of ServerB```

```UserA appears in the nicklist of #ChanA on ServerA```
```UserA Does not appear in the nicklist of #ChanB on ServerB```

This issue also seems to effect the voice status
UserA is connected to ServerA's voice channel ChanA and decides to join ServerB's voice channel ChanB the following appears in &bitlbee
`discord - User UserA is no longer in any voice channel.`

**Comment by sm00th** [comment]
c71bc10 should fix this. Unfortunately I currently don't have a proper way to test this, can you check if this commit resolves the issue?

**Comment by mumixam** [comment]
ok, i tried it out and it appears to be working so far!
