### ISSUE TITLE
configure not respecting --prefix

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#35]
Not sure if I'm missing something, but regardless of --prefix value, it always installs to /usr/lib/bitlbee.

Here is the full log: http://pastie.org/pastes/10863398/text?key=ndgrgrtdxrhcsvmjcjbmiw

The timestamps on /usr/lib/bitlbee is correct to the time when I ran `make install`

**Comment by dequis** [comment]
Because it doesn't use prefix, it uses plugindir, which is taken from the pkg-config of the bitlbee installation. You can override it, from the readme:

> If your bitlbee's plugindir is in non-standard location you can specify it by calling ./configure with --with-plugindir=/path/to/plugindir option.

**Comment by Kays** [comment]
@dequis ah thanks!
