### ISSUE TITLE
IDEA: Prepand channel names with  discord server name

### ISSUE THREAD

**Issue by GhettoGirl** [sm00th/bitlbee-discord#39]
Wouldn't a channel name be more recognizable in the IRC client if it was prepaned with the discord server name if someone has joined multiple servers at once.
Example: ```#mydiscordserver_channelname```

**Comment by sm00th** [comment]
There is a `server_prefix_len` account option that does what you describe. You can find more info about it in README.

**Comment by GhettoGirl** [comment]
ok thanks
