### ISSUE TITLE
Different nickname per discord server

### ISSUE THREAD

**Issue by erockce** [sm00th/bitlbee-discord#40]
Enhancement request.

As a user I'd like the ability to set a different nickname based on the Discord server I am on.  When connecting using the `bitlbee-discord` plugin, the nickname is set by your Discord login name.

The Discord web-based and application clients let you change your nick name on a per server basis.  I've set this preference for each server I wish to override the default.

However when I login to Discord with Bitlbee + ``bitlbee-discord``, my Discord login name is used as the nickname.

Since Bitlbee is the gateway into different chat systems such as discord, a configuration plugin option should be used.

**Comment by sm00th** [comment]
It took me a while to get to this. As with #55 there is no way to display your nickname differently in bitlbee for different discord channels. When you send messages the configured username will be used on discord's side, so it will show up correctly for everyone but you.
