### ISSUE TITLE
Bitlbee Crash on Discord-Channel /part

### ISSUE THREAD

**Issue by romibi** [sm00th/bitlbee-discord#42]
Discord-Plugin Version: | git-master from 2016-08-05 ( d7fb6b1 ?)
---|---
BitlBee Version: | apt-get package "bitlbee-libpurple" (3.4.1-1 0  http://ports.ubuntu.com/ wily/universe armhf )
Setup: | Raspberry Pi 2 with Ubuntu Mate 15.10

Issue:
Wanting to remove Discord channels from the Channel-List by using /part (and clear Chatlog in client) crashes Bitlbee resulting in a DC…

Reason I want to part them is the problem mentioned in Issue #34 

It does not seem related to the IRC Client … I tested it with Quassel and HexChat …
Parting Channels from other Bitlbee Plugins is fine …

Crashlog:
http://pastebin.com/mcLvAUSj

**Comment by sm00th** [comment]
Tried to reproduce it with irssi and hexchat, I was able to close channels/part channels with both of them without any issue.
Are you doing anything tricky (e.g. parting channels by a script/autocmd)? Can you reproduce it on x86_64 or it is just armhf?
It would also help to have a good backtrace, can you rebuild bitlbee-discord with "CFLAGS="-O0 -g3 ./configure" and try to get the backtrace again? It should build with "-O2 -g" by default which should be enough but maybe that is different for armhf for some reason.

You might also try with an upstream bitlbee version, not the distro one, you can find more info [here](http://code.bitlbee.org/debian/README.html).

**Comment by romibi** [comment]
I'm using a simple `/part` …
Yes I can test the things with x86_64, debug rebuild and upstream bitlbee version …
But I don't know when … (I'm having exams the next few weeks)

**Comment by dequis** [comment]
There are armhf builds in that repo. I do remember fixing things like this at some point, just not sure when, so please use the latest version.

**Comment by romibi** [comment]
yes the version in that repo works fine
(`deb http://code.bitlbee.org/debian/master/wily/armhf/ ./`)
