### ISSUE TITLE
non-ascii characters breaking mentions

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#45]
Example, someone with `name (ᵔᴥᵔ)` as his username breaks mentions. It doesn't show up in bitlbee-discord and `name_:` does not convert into a mention properly

**Comment by sm00th** [comment]
you can enable utf8 nicks in bitlbee as a workaround, to do that do `set utf8_nicks true` in the control channel and reconnect to discord.

**Comment by Kays** [comment]
Oh! That does resolve the first part. Thank you!

**Comment by sm00th** [comment]
5cec960 should fix this on both master and listchan branches.
