### ISSUE TITLE
Login error: (null) when password includes special characters

### ISSUE THREAD

**Issue by Mossepo** [sm00th/bitlbee-discord#46]
<del>Noticed that I couldn't log in to my account when my password included characters like ~`/{ and so forth.</del>

<del>Was welcomed with this:
@root discord - Login error: (null)
@root discord - Logging in: Signing off..
@root discord - Logging in: Reconnecting in 5 seconds..</del>

<del>Changed my password and it works like a charm. </del>
<del> Using bitlbee-discord-git-121.c4f3426-1 from AUR.</del>

EDIT: Seems it has nothing to do with the plugin, just need to input the password in quotes; https://bugs.bitlbee.org/ticket/758

**Comment by tsudoko** [comment]
Same issue here, but it doesn't matter if the password contains special characters or not; changing the password doesn't fix it too. Using bitlbee-discord c4f3426 with bitlbee 3.4.2+20160823+master+52-g2dc394c-git

**Comment by sm00th** [comment]
Closing this now since it was a generic bitlbee issue. Reopen if needed.
