### ISSUE TITLE
Some messages getting lost

### ISSUE THREAD

**Issue by zertap** [sm00th/bitlbee-discord#48]
Sometimes messages typed on the IRC end won't get through to the discord side.
I suspect this is the same thing that happens in the actual client too, which then marks your messages with red color to indicate the sending failed.
There isn't any indication of failing to send messages in the plugin.

It would be really appreciated if there would be some kind of check-up if the message was succesfully delivered, and if not, a notification or automatic re-send.

**Comment by zertap** [comment]
Actually, I just noticed: There actually is a message about this; on the main bitlbee channel.
I think this should be displayed on the channel the message failed to be sent. Kinda like the urlinfo.

**Comment by sm00th** [comment]
Yes, the error messages, warnings and all of the technical info are shown in bitlbee's control channel. This workflow always  was in core bitlbee and all of the plugins, so I am trying to stay consistent with that. Urlinfo is a different matter as it's message expansion, not technical information. Control channel isn't usually very noisy so when it lights up you better see what happened.
