### ISSUE TITLE
[listchan] Channels still marked as read without adding chat

### ISSUE THREAD

**Issue by digitalcircuit** [sm00th/bitlbee-discord#52]
### In short
* In [```listchan``` branch](https://github.com/sm00th/bitlbee-discord/tree/listchan), channels that haven't been ```chat add```'d still mark messages as read
 * Prevents catching up on the Discord website with no way to check what you've actually seen
 * Possibly make ```send_acks``` into tri-state, with ```always```, ```joined``` (*default*), ```never```

### Thoughts
In the ```listchan``` branch, by default no channels are joined, yet all messages are marked as read.  Originally, I expected only joined channels (*```chat add discord [index]```*) to be marked as read.

I join two Discord groups mostly for keeping up with the individuals on them, not the actual server channels.  However, every now and then I'd still like to catch up on the channels right now, without wanting all of it in my IRC client.

Others may have different use cases, so keeping some form of disabling message acknowledgement makes sense.  Some might prefer marking all channels as read.. though that use case might be better handled by muting channels.

**Comment by sm00th** [comment]
918ba59 changes the logic so that only messages sent to bitlbee will be acked. Not changing send_acks option at this time as acking messages that you couldn't have seen is a very strange usecase.

**Comment by digitalcircuit** [comment]
That makes sense.  Thanks for the quick response!
