### ISSUE TITLE
Renamed nicks don't highlight properly

### ISSUE THREAD

**Issue by stevesbrain** [sm00th/bitlbee-discord#56]
It appears that if you rename a nick, locally, it won't get automatically translated into a discord-compatible highlight (like it would if you just used a non-renamed nick). Given that server names are shown instead of nicknames anyway, I would think a local rename should also be able to be successfully translated into discord-compatible highlights :)

**Comment by sm00th** [comment]
5cec960 should fix this on both master and listchan branches.
