### ISSUE TITLE
A command to get the previous n pins on channel/server

### ISSUE THREAD

**Issue by zertap** [sm00th/bitlbee-discord#59]
https://discordapp.com/developers/docs/resources/channel#get-pinned-messages

If bitlbee supports supplying commands to a plugin, this could be nice.
Maybe with syntax like:
get pins
 _server_ [_all_ | _channel_]
 _all-servers_

**Comment by sm00th** [comment]
I don't think that a separate command is a good idea, but it can be a new option to dump them on join. Besides it looks like getting list of pinned messages would be needed anyways to fix #69

**Comment by zertap** [comment]
That would be alright too. TBH if pins would just be prefixed with "PIN:" or something, I could just filter them to another buffer on clientside.

**Comment by sm00th** [comment]
as mentioned previously it is not implemented as a command, but as an account option. `fetch_pinned` (disabled by default) would allow you to fetch pinned messages on join.
