### ISSUE TITLE
Unread Indicators

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#6]
bitlbee-discord messes up all the unread indicators (and notification alerts) on my Discord apps, on both my computer and mobile devices.

I don't know if it's possible to not auto-mark all messages as read.

**Comment by sm00th** [comment]
Added an option to disable this in 303c777. Just do `acc discord set disable_acks on` to disable marking messages as read. However, it looks like discord will automatically mark all messages as read in a channel when *you* send a message to that channel and there is no way to affect that behavior.

**Comment by sm00th** [comment]
Inverted the logic and renamed disable_acks to send_acks in de68da4.
