### ISSUE TITLE
Pins and depins displayed as edits.

### ISSUE THREAD

**Issue by zertap** [sm00th/bitlbee-discord#69]
I just noticed that when a message is pinned or removed from pinned messages, the message is then outputted again with the edit prefix.

I guess this is because whether a message is pinned or not is stored in the message data itself.
Thus a check if the message has been pinned or depinned and if the message text has been modified would allow you to filter out the pins and depins, or display them with their own prefix.

This is especially noticeable on channels where a lot of pins are used and removed, since weeks or months old messages suddenly get "edited" without any changes to them.

**Comment by sm00th** [comment]
`88de238` adds this feature. It needs `fetch_pinned` option to be enabled to work properly.
