### ISSUE TITLE
My Messages from Discord Apps Don't Show

### ISSUE THREAD

**Issue by Kays** [sm00th/bitlbee-discord#7]
My messages that I type in Discord apps (mobile or desktop) don't show up in bitlbee-discord so the convo looks very awkward there.

**Comment by sm00th** [comment]
This is not likely to happen for a couple of reasons:
 - while bitlbee does support the notion of "selfmessages" (aka messages sent from other clients/locations) it does not export this functionality to plugins, only to internal protocol implementations (which might be a bug).
 - even if we bypass(or fix) the first issue, there is no way to tell apart a message sent from bitlbee and a message sent from webapp/mobile in discord. So by printing messages from "self" we'll get an echo for every message sent from bitlbee.

**Comment by Kays** [comment]
Okay; I understand. I, personally, would not mind seeing my own message duplicated if that is the only "bug" because the conversation would at least be continuous (not broken), similar to how bitlbee's twitter echos my tweet back at me. I can understand if others do not like seeing their message echo'd back at them.

**Comment by sm00th** [comment]
Leaving this open, maybe someone can come up with a sane solution or they'll change the api to include client info for every message. For reference a [gist](https://gist.github.com/sm00th/eab69cebf3400f2491b1) with a patch that enables selfmessages and kinda tries to track sent messages but fails miserably most of the time.

**Comment by jgeboski** [comment]
Proper self messaging support has been implemented upstream (see: bitlbee/bitlbee@345577b). It should be quite simple to do. I would look at the Facebook plugin for an example (bitlbee/bitlbee-facebook@55182f5).

**Comment by sm00th** [comment]
> Proper self messaging support has been implemented upstream (see: bitlbee/bitlbee@345577b)

Thanks, but while it solves the first issue from my [previous comment](https://github.com/sm00th/bitlbee-discord/issues/7#issuecomment-168346740), I still have no means of canceling server echoes, unless discord changes their API.

**Comment by romibi** [comment]
Why not just (only) ignore own messages if they match the last sent message(s)?

**Comment by sm00th** [comment]
> Why not just (only) ignore own messages if they match the last sent message(s)?

Storing one message is not enough due to possible latencies, storing all messages until you get an ack could work, but again you need to make sure that that "cache" is getting cleaned if for some reason you don't get a server echo. All in all this is a lot of unnecessary work for a feature that I don't believe to be necessary.

So I am not doing this unless there is an easy way to determine message's origin from discord's data. I am willing to accept patches though.

**Comment by romibi** [comment]
hm true … and i assume bitlbee does not support preventing to show sent messages …
that way you could just only show the echos …

**Comment by fiiim** [comment]
It works the other way around though, if you type something in the bitlbee-discord it shows in the discord app. But not if you type stuff in the discord app. Why is this? cant this behavior be replicated or something?
