### ISSUE TITLE
Autojoining

### ISSUE THREAD

**Issue by Sophira** [sm00th/bitlbee-discord#74]
I understand that the behaviour now is for channels to not be autojoined, and I understand that this is normally a good thing. I also understand that channels can be added manually using `chat list` and `chat add`, and set to auto join with `chan set`.

However, I personally preferred the old behaviour - to autojoin all channels on connect. I understand that my preference is probably quite strange in this respect but it works better with the way I interact with Discord, and as I understand it, without doing that people can see you in the names list of all channels anyway and might believe you would be notified of new messages for you, when in fact that isn't the case.

I asked trac3r about this on IRC and apparently there's a reason for not including this as an option. If I knew this reason I'd be willing to try patching this myself as an option!

One other question - if autojoining isn't (and in case it'll never be) an option, does the `server_prefix_len` option mean anything?

**Comment by sm00th** [comment]
I'll take a look and try to find what the issue was and if it is still there.

As for server_prefix_len it has a meaning in case when you are a part of multiple "guilds" making it easier for user to distinguish between channels with same names and helps a bit in making chan names unique: https://github.com/sm00th/bitlbee-discord/commit/c6b5bc44a14c2a5ec7facf06a43e9502fe7cbcf7

**Comment by MuffinMedic** [comment]
Seconded. Autojoin all channels on connect + if possible, auto join when you join a new one Discord side would be great.

**Comment by featheredtoast** [comment]
Another request for autojoin all channels... Any updates on this? My channel operator has a tendancy to rename the general chat for shenanegans names, and it'd be nice to be able to auto-follow/join the channels through renames.

**Comment by squigglezworth** [comment]
+1

**Comment by sm00th** [comment]
Fixed by #129 but off by default, so you'll need to enable it.
