### ISSUE TITLE
Unable to build on ubuntu 16.10

### ISSUE THREAD

**Issue by AdrianKoshka** [sm00th/bitlbee-discord#79]
It seems the version of bitlbee packaged with ubuntu isn't satisfactory for building `bitlbee-discord`? I just want to confirm this:

I get stuck on `./configure`

```
checking for BITLBEE... no
configure: error: Package requirements (bitlbee >= 3.5) were not met:

Requested 'bitlbee >= 3.5' but version of bitlbee is 3.4.2-1.1

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BITLBEE_CFLAGS
and BITLBEE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I know (and double checked) that I have `bitlbee-dev` installed (just updated `bitlbee-facebook` recently...so it must be there ;P).

**Comment by dequis** [comment]
Yes.

http://code.bitlbee.org/debian/README.html

I think yakkety isn't there but xenial should do.

**Comment by AdrianKoshka** [comment]
Hrmm, so you're saying even though I'm on yakkety I should be able to grab the xenial packages?

**Comment by dequis** [comment]
Yeah, probably. If it throws dependency errors then I'm wrong and you'll have to do things the hard way (or upgrade to ubuntu 17.04 beta 2, which will be released in a couple of weeks)

**Comment by AdrianKoshka** [comment]
Thanks, works now!
