### ISSUE TITLE
[Feature Request] Only Show friends in the control Channel buddy list

### ISSUE THREAD

**Issue by ioangogo** [sm00th/bitlbee-discord#89]
This will declutter that list and only show users that are you friends in the list

This could be a setting

**Comment by sm00th** [comment]
Theoretically we can skip status changes for non-friends and thus keep them offline, but I don't think there is a way to still show them in channel name lists and not show them in control channel lists. So that would mean that only people from your friendlist would be visible everywhere.

**Comment by dequis** [comment]
You can keep them offline and they will be visible in groupchats. That's how it works in twitter/jabber/etc

**Comment by sm00th** [comment]
Nice, then it is feasible.

**Comment by ioangogo** [comment]
I think it might be possible to put the members of rooms only in the rooms. The mqtt Facebook plugin does this, it only puts your friends in the ```&bitlbee``` control room and members of groups chats who are not your friends only appear in the group

**Comment by Sophira** [comment]
This is something I'd like, too. I'm looking into it at the moment.
