### ISSUE TITLE
Login error: Failed to parse json reply.

### ISSUE THREAD

**Issue by spyn** [sm00th/bitlbee-discord#90]
Hey, first time user. Having some issues logging in after compiling the source from git...

```
discord - Login error: Failed to parse json reply.
discord - Logging in: Signing off..
discord - Logging in: Reconnecting in 15 seconds..
```

Freshly built bitlbee from git: 
BitlBee 3.5.1+20170529+master+18-gb9c10a1-git

From debug: 

```
About to send HTTP request:
POST /api/auth/login HTTP/1.1
Host: discordapp.com
User-Agent: Bitlbee-Discord
Content-Type: application/json
Content-Length: 56

{"email":"xxx@gmail.com","password":"xxx"}
1 There was an error parsing the OCSP response: ASN1 parser: Error in DER parsing..
[13:26:56] <<< ((null)) discord_http_login_cb [0] 0
(null)

[13:27:41] >>> ((null)) discord_http_login 192
```

**Comment by sm00th** [comment]
That seems to be an issue with ssl lib. Is that issue persistent? What library are you using for ssl (gnutls? openssl?) you can try updating or switching to another library and rebuilding bitlbee to see if that helps.

**Comment by spyn** [comment]
Currently using gnutls (2.12.23-12ubuntu2) - will update and see how I go, thanks!

**Comment by sm00th** [comment]
You can try using prebuilt bitlbee nightly ubuntu packages from http://code.bitlbee.org/debian/README.html instead of compiling it yourself.

**Comment by untoreh** [comment]
getting this error on alpine
