### ISSUE TITLE
Installed from AUR and Weechat doesn't recognize the plugin

### ISSUE THREAD

**Issue by Hund** [sm00th/bitlbee-discord#96]
I'm running Arch Linux with Bitlbee 3.5.1 and I just installed the package `bitlbee-discord-git` from AUR, I restarted Bitlbee and it doesn't recognize the new plugin.

```
/usr/lib/bitlbee:
-rwxr-xr-x 1 root root 42K Aug 14 18:08 discord.so
-rwxr-xr-x 1 root root 48K Feb  1  2017 otr.so
-rwxr-xr-x 1 root root 35K Feb  1  2017 skype.so
```

What's wrong?

**Comment by sm00th** [comment]
Did you disconnect all clients before restarting? You can also try starting bitlbee by hand in foreground as `bitlbee -nvD` and see if bitlbee issues any warnings about discord.so,

**Comment by Hund** [comment]
Oh, wait, I'm a complete idiot.. I forgot to restart Bitlbee. :|
